### ISSUE TITLE
"Could not get endpoint url" error when running locally through Docker

### ISSUE THREAD

**Issue by Buuntu** [pynamodb/PynamoDB#779]
I'm having trouble running dynamodb locally, with the following docker container [aws/dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local/).

When I set the host parameter to http://localhost:8000, I get the following error when trying to do a scan:
```bash
pynamodb.exceptions.ScanError: Failed to scan table: Could not connect to the endpoint URL: "http://localhost:8000/"
```

My model:
```python
class ExampleModel(Model):
    """
    Some Model
    """

    class Meta:
        table_name = 'example_model'
        host = "http://localhost:8000"
```

I know the pynamodb connection is working because I can go to `http://localhost:8000/shell` and use boto3 to list the tables.

I'm using docker-compose for both the Flask/PynamoDB and a DynamoDB container, with ports 5000 and 8000 exposed respectively.

Using PynamoDB 4.3.1.

**Comment by Buuntu** [comment]
Do you have to set `aws_secret_access_key` and `aws_access_key_id` properties in the `Meta` class as well, when `host` is provided?  The docs are unclear to me whether this is the issue.  I've tried with both of those set in the environment and unset and it's the same thing, where does PynamoDB find these by default?  In your env or in ~/.aws?

I'd rather not have to set those for every table if possible.  What do others do when developing locally?

**Comment by ikonst** [comment]
PynamoDB uses boto to connect, and it inherits its behavior, so it would use the environment variables, etc. You do not have to specify the keys in the Meta class.

**Comment by holyoaks** [comment]
I have this issue as well. Identical behavior, except I'm using Django instead of Flask, and PynamoDB 4.3.3

**Comment by pyros2097** [comment]
It works fine for me,
```python
from pynamodb.attributes import UnicodeAttribute
from pynamodb.models import Model, PAY_PER_REQUEST_BILLING_MODE

class UserModel(Model):
    class Meta:
        table_name = "dynamodb-user"
        host = "http://localhost:8000"
    email = UnicodeAttribute(null=True)
    first_name = UnicodeAttribute(range_key=True)
    last_name = UnicodeAttribute(hash_key=True)

def main():
    UserModel.create_table(billing_mode=PAY_PER_REQUEST_BILLING_MODE)
    user = UserModel("John", "Denver")
    user.email = "djohn@company.org"
    user.save()
    print(user)

main()
```
docker ps
```bash
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
7151467bc834        amazon/dynamodb-local   "java -jar DynamoDBL…"   2 minutes ago       Up 2 minutes        0.0.0.0:8000->8000/tcp   heuristic_grothendieck
```
aws dynamodb list-tables --endpoint-url http://localhost:8000
```bash
{
    "TableNames": [
        "dynamodb-user"
    ]
}
```

**Comment by mila411** [comment]
In my case it was FastAPI, but I was getting a similar error with get() instead of scan. @ikonst  reply was all the answer I needed.

So, I set the same AWS credentials for dynamo-local, and pynamodb:

```yaml
version: "3.7"
services:
  pynamodb:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy

  dynamodb-local:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - 8000:8000
```

I was creating table in terraform, which confused me even more. In any case, I don't think this is a pynamodb problem.
